/**
 * Better Genshin Impact JavaScript
 * Bundled with BetterGI CLI (https://www.npmjs.com/package/@bettergi/cli)
 *
 * This file is automatically generated and should not be edited.
 */
import { __name } from "./libs/rolldown-runtime.js";
import { exitLobbyToTeyvat } from "./libs/modules/lobby.js";
import { execDailyTask } from "./libs/workflows/daily.js";
import { execWeeklyTask } from "./libs/workflows/weekly.js";

//#region main.ts
(async function () {
  //! 初始化游戏环境
  setGameMetrics(1920, 1080, 1.5);
  await genshin.returnMainUi();
  //! 执行每周任务
  await execWeeklyTask();
  //! 执行每日任务
  await execDailyTask();
  //! 返回提瓦特大陆
  await exitLobbyToTeyvat();
})();

//#endregion
