// ============================================================
// GOOD v3 Format Constants — Chinese to English Key Mappings
// ============================================================

// --- Stat Keys ---
// Maps Chinese stat names to GOOD stat keys.
// For "生命值", "攻击力", "防御力": use "_" suffix for percent, flat otherwise.
var STAT_KEY_MAP = {
    "生命值": { flat: "hp", percent: "hp_" },
    "攻击力": { flat: "atk", percent: "atk_" },
    "防御力": { flat: "def", percent: "def_" },
    "元素精通": "eleMas",
    "元素充能效率": "enerRech_",
    "暴击率": "critRate_",
    "暴击伤害": "critDMG_",
    "治疗加成": "heal_",
    "物理伤害加成": "physical_dmg_",
    "火元素伤害加成": "pyro_dmg_",
    "雷元素伤害加成": "electro_dmg_",
    "水元素伤害加成": "hydro_dmg_",
    "草元素伤害加成": "dendro_dmg_",
    "风元素伤害加成": "anemo_dmg_",
    "岩元素伤害加成": "geo_dmg_",
    "冰元素伤害加成": "cryo_dmg_"
};

// All stat name strings for OCR matching (ordered by length descending for greedy match)
var STAT_NAMES = [
    "物理伤害加成", "火元素伤害加成", "雷元素伤害加成", "水元素伤害加成",
    "草元素伤害加成", "风元素伤害加成", "岩元素伤害加成", "冰元素伤害加成",
    "元素充能效率", "元素精通", "暴击伤害", "暴击率", "治疗加成",
    "生命值", "攻击力", "防御力"
];

// --- Artifact Slot Keys ---
var SLOT_KEY_MAP = {
    "生之花": "flower",
    "死之羽": "plume",
    "时之沙": "sands",
    "空之杯": "goblet",
    "理之冠": "circlet"
};

// --- Load mapping data from external JSON ---
// data/mappings.json is generated by an external tool and contains
// characters, weapons, and artifact sets with their GOOD keys, rarities, and localized names.
var MAPPINGS = JSON.parse(file.readTextSync("data/mappings.json"));

var CHARACTER_NAME_MAP = {};
var CHARACTER_CONST_BONUS = {};
for (var i = 0; i < MAPPINGS.characters.length; i++) {
    var c = MAPPINGS.characters[i];
    CHARACTER_NAME_MAP[c.names.zh] = c.id;
    if (c.c3 || c.c5) {
        CHARACTER_CONST_BONUS[c.id] = { c3: c.c3 || null, c5: c.c5 || null };
    }
}

var WEAPON_NAME_MAP = {};
for (var i = 0; i < MAPPINGS.weapons.length; i++) {
    var w = MAPPINGS.weapons[i];
    WEAPON_NAME_MAP[w.names.zh] = w.id;
}

var ARTIFACT_SET_MAP = {};
for (var i = 0; i < MAPPINGS.artifactSets.length; i++) {
    var a = MAPPINGS.artifactSets[i];
    ARTIFACT_SET_MAP[a.names.zh] = a.id;
}

// 套装最高星级映射
var ARTIFACT_SET_MAX_RARITY = {};
for (var i = 0; i < MAPPINGS.artifactSets.length; i++) {
    var a = MAPPINGS.artifactSets[i];
    ARTIFACT_SET_MAX_RARITY[a.id] = a.rarity;
}

var WEAPON_1_2_STAR = [];
for (var i = 0; i < MAPPINGS.weapons.length; i++) {
    var w = MAPPINGS.weapons[i];
    if (w.rarity <= 2) WEAPON_1_2_STAR.push(w.id);
}

// Apply user name overrides for characters with customizable in-game names
var NAME_OVERRIDES = [
    { setting: "travelerName", id: "Traveler" },
    { setting: "wandererName", id: "Wanderer" },
    { setting: "manekinName", id: "Manekin" },
    { setting: "manekinaName", id: "Manekina" }
];
for (var i = 0; i < NAME_OVERRIDES.length; i++) {
    var override = NAME_OVERRIDES[i];
    var customName = settings[override.setting];
    if (customName && typeof customName === "string" && customName.trim()) {
        CHARACTER_NAME_MAP[customName.trim()] = override.id;
    }
}

// --- Level to Ascension Lookup ---
// Given a character/weapon level, determine the maximum possible ascension
// Ascension boundaries: 20→0, 40→1, 50→2, 60→3, 70→4, 80→5, 90→6
function levelToAscension(level) {
    if (level <= 20) return 0;
    if (level <= 40) return 1;
    if (level <= 50) return 2;
    if (level <= 60) return 3;
    if (level <= 70) return 4;
    if (level <= 80) return 5;
    return 6;
}

// --- Helper: Parse a stat from OCR text ---
// Returns { key: "statKey", value: number } or null
function parseStatFromText(text) {
    if (!text || typeof text !== "string") return null;
    text = text.replace(/,/g, "").trim();

    for (var i = 0; i < STAT_NAMES.length; i++) {
        var name = STAT_NAMES[i];
        if (text.indexOf(name) === -1) continue;

        var isInactive = text.indexOf("待激活") !== -1;
        var hasPercent = text.indexOf("%") !== -1;

        // Extract numeric value
        var numMatch = text.match(/[\+\s]([\d]+\.?\d*)/);
        var value = numMatch ? parseFloat(numMatch[1]) : 0;

        var statEntry = STAT_KEY_MAP[name];
        var key;
        if (typeof statEntry === "object") {
            // hp, atk, def — distinguish flat vs percent
            key = hasPercent ? statEntry.percent : statEntry.flat;
        } else {
            key = statEntry;
        }

        return {
            key: key,
            value: isInactive ? 0 : value,
            inactive: isInactive
        };
    }
    return null;
}

// --- Helper: Fuzzy match a string against a map ---
// Returns the best matching key from the map, or null
// OCR 常见混淆字对: [错误字, 正确字]
var OCR_CONFUSIONS = [
    ["茲", "兹"],
    ["兹", "茲"]
];

function fuzzyMatchMap(text, map) {
    if (!text) return null;
    // Clean OCR text: remove non-CJK/non-alphanumeric noise
    var cleaned = text.replace(/[^\u4E00-\u9FFF\u300C\u300Da-zA-Z0-9]/g, "").trim();
    if (!cleaned) return null;

    // Try OCR confusion substitutions
    for (var ci = 0; ci < OCR_CONFUSIONS.length; ci++) {
        var from = OCR_CONFUSIONS[ci][0], to = OCR_CONFUSIONS[ci][1];
        if (cleaned.indexOf(from) !== -1) {
            var alt = cleaned.replace(new RegExp(from, "g"), to);
            if (map[alt] !== undefined) return map[alt];
        }
    }

    // Exact match first
    if (map[cleaned] !== undefined) return map[cleaned];

    // Try substring match (OCR may include extra characters)
    var bestMatch = null;
    var bestLen = 0;
    for (var cn in map) {
        if (cleaned.indexOf(cn) !== -1 && cn.length > bestLen) {
            bestMatch = map[cn];
            bestLen = cn.length;
        }
        if (cn.indexOf(cleaned) !== -1 && cleaned.length > bestLen) {
            bestMatch = map[cn];
            bestLen = cleaned.length;
        }
    }
    if (bestMatch) return bestMatch;

    // Levenshtein distance fallback for short strings
    var minDist = Infinity;
    for (var cn2 in map) {
        var dist = levenshtein(cleaned, cn2);
        if (dist < minDist && dist <= Math.max(1, Math.floor(cn2.length * 0.3))) {
            minDist = dist;
            bestMatch = map[cn2];
        }
    }
    return bestMatch;
}

// Simple Levenshtein distance
function levenshtein(a, b) {
    var m = a.length, n = b.length;
    var dp = [];
    for (var i = 0; i <= m; i++) {
        dp[i] = [i];
        for (var j = 1; j <= n; j++) {
            if (i === 0) { dp[i][j] = j; continue; }
            dp[i][j] = Math.min(
                dp[i - 1][j] + 1,
                dp[i][j - 1] + 1,
                dp[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1)
            );
        }
    }
    return dp[m][n];
}
